stages:
  - release

release_job:
  stage: release
  image: python:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - export VERSION=$(python -c "from middle_layer_server import __version__; print(__version__)")
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$VERSION'
    description: '$VERSION'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.
