image: python:latest

stages:
  - test
  - lint
  - release

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

Unit Tests:
  stage: test
  script:
    - poetry run pytest tests

Python Code Lint:
  stage: lint
  script:
    - poetry run black .

Release:
  stage: release
  needs: [Unit Tests]
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "This is the build stage"
    - poetry config repositories.gitlab https://gitlab.desy.de/api/v4/projects/5555/packages/pypi
    - echo "Repository gitlab configured ..."
    - poetry build
    - echo "Build done ..."
    - poetry publish --repository gitlab -u gitlab+ci+release+token -p 42BTg_yJJ3SsSyRV4QFx
    - echo "Publishing done!"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
